spring:
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  security:
    user:
      name: ${REST_USER}
      password: ${REST_PASSWORD}

server:
  port: ${PORT}
  servlet:
    context-path: /onap/policy/clamp/acelement/v2
  ssl:
    enabled: false
  error:
    path: /error

element:
  elementId:
    name: ${ELEMENT_ID}
    version: ${ELEMENT_VERSION}
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
